development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: zombie_box_dev
  pool: 500
  host: localhost
  username: postgres
  password: password
  password: password

test:
    adapter: postgresql
    encoding: utf8
    reconnect: false
    database: zombie_box_test
    pool: 5
    host: localhost
    username: postgres
    password: password

production:
    adapter: postgresql
    encoding: utf8
    reconnect: false
    database: d85j68vua3mpp0
    pool: 200 
    host: ec2-50-19-208-138.compute-1.amazonaws.com
    port: 5432
    username: utrrhvfbgrydtz
    password: fIzDFt9cKGp4LMrc6tIlvA63WP
